import { db } from "../lib/db";
import { releaseTemplates } from "./schema";

// Join lines into a markdown body. Double-quoted strings keep ${...} and ```
// literal, so placeholders and code fences survive as-is.
const md = (...lines: string[]) => lines.join("\n");

type Seed = {
  category: string;
  name: string;
  repo: string;
  bodyJa: string;
  bodyEn: string;
  bodyVi: string;
};

const templates: Seed[] = [
  {
    category: "Header",
    name: "Header — PRs to be released",
    repo: "",
    bodyJa: md("リリースする PR は以下の通り", "", "${pr_list}", "", "以下の手順でリリースを行う"),
    bodyEn: md("PRs to be released:", "", "${pr_list}", "", "The release will be performed according to the procedure below."),
    bodyVi: md("Những PR cần release:", "", "${pr_list}", "", "Quy trình release được thực hiện theo các bước dưới đây."),
  },
  {
    category: "Common",
    name: "Merge PR to master",
    repo: "",
    bodyJa: md("1. **以下の PR をマージする**", "", "${pr_list}"),
    bodyEn: md("1. **Merge the following PR**", "", "${pr_list}"),
    bodyVi: md("1. **Merge PR sau**", "", "${pr_list}"),
  },
  {
    category: "Common",
    name: "Update submodule (config/migration)",
    repo: "",
    bodyJa: md(
      "1. **air-closet-config の PR をマージする**",
      "",
      "   - [ ] air-closet-config: ${config_pr_url}",
      "",
      "2. **submodule を更新する**",
      "",
      "   ```bash",
      "   TARGET_BRANCH=${target_branch}",
      "   PROJECT_NO=${task}",
      "   TARGET_SUBMODULE=air-closet-config",
      "   git checkout $TARGET_BRANCH && git pull origin $TARGET_BRANCH",
      "   cd $TARGET_SUBMODULE && git checkout master && git pull origin master && cd ..",
      "   git add $TARGET_SUBMODULE",
      '   git commit -m ":wrench: $PROJECT_NO: update $TARGET_SUBMODULE"',
      "   git push origin $TARGET_BRANCH",
      "   ```",
    ),
    bodyEn: md(
      "1. **Merge the air-closet-config PR**",
      "",
      "   - [ ] air-closet-config: ${config_pr_url}",
      "",
      "2. **Update the submodule**",
      "",
      "   ```bash",
      "   TARGET_BRANCH=${target_branch}",
      "   PROJECT_NO=${task}",
      "   TARGET_SUBMODULE=air-closet-config",
      "   git checkout $TARGET_BRANCH && git pull origin $TARGET_BRANCH",
      "   cd $TARGET_SUBMODULE && git checkout master && git pull origin master && cd ..",
      "   git add $TARGET_SUBMODULE",
      '   git commit -m ":wrench: $PROJECT_NO: update $TARGET_SUBMODULE"',
      "   git push origin $TARGET_BRANCH",
      "   ```",
    ),
    bodyVi: md(
      "1. **Merge PR air-closet-config**",
      "",
      "   - [ ] air-closet-config: ${config_pr_url}",
      "",
      "2. **Cập nhật submodule**",
      "",
      "   ```bash",
      "   TARGET_BRANCH=${target_branch}",
      "   PROJECT_NO=${task}",
      "   TARGET_SUBMODULE=air-closet-config",
      "   git checkout $TARGET_BRANCH && git pull origin $TARGET_BRANCH",
      "   cd $TARGET_SUBMODULE && git checkout master && git pull origin master && cd ..",
      "   git add $TARGET_SUBMODULE",
      '   git commit -m ":wrench: $PROJECT_NO: update $TARGET_SUBMODULE"',
      "   git push origin $TARGET_BRANCH",
      "   ```",
    ),
  },
  {
    category: "Common",
    name: "Execute SQL",
    repo: "",
    bodyJa: md(
      "1. **SQL の実行**",
      "",
      "   - [ ] 以下の SQL を実行する（Slack レビュースレッド: ${slack_thread}）",
      "",
      "     ```sql",
      "     -- 実行する SQL をここに記載",
      "     ```",
      "",
      "2. **SQL が実行されたことの確認**",
      "",
      "   - [ ] 確認用 SQL を実行し、データが書き換えられていることを確認する",
    ),
    bodyEn: md(
      "1. **Execute SQL**",
      "",
      "   - [ ] Execute the following SQL (Slack review thread: ${slack_thread})",
      "",
      "     ```sql",
      "     -- Enter SQL to execute here",
      "     ```",
      "",
      "2. **Confirm SQL execution**",
      "",
      "   - [ ] Run the confirmation SQL and verify the data was updated correctly",
    ),
    bodyVi: md(
      "1. **Chạy SQL**",
      "",
      "   - [ ] Chạy SQL sau (Link thread Slack review: ${slack_thread})",
      "",
      "     ```sql",
      "     -- Điền SQL cần chạy ở đây",
      "     ```",
      "",
      "2. **Xác nhận đã chạy SQL**",
      "",
      "   - [ ] Chạy SQL confirm và xác nhận data đã được cập nhật đúng",
    ),
  },
  {
    category: "Mall",
    name: "Release acm-admin-api",
    repo: "acm-admin-api",
    bodyJa: md(
      "1. **以下の PR をマージする**",
      "",
      "   - [ ] acm-admin-api: ${pr_url}",
      "",
      "2. **本番にリリースする**",
      "",
      "   - [ ] release コマンドを実行する",
      "",
      "     ```bash",
      "     git checkout ${branch}",
      "     git pull origin ${branch}",
      "     yarn build",
      "     cd ecspresso/",
      "     sh migration.sh prod",
      "     sh deploy.sh prod",
      "     ```",
      "",
      "   - [ ] release コマンド内で表示される SHA1 が最新の master と一致している",
      "",
      "3. **リリースできているかの確認**",
      "",
      "   - [ ] 以下のコマンドで、リリースされた SHA1 が最新の master と一致することを確認する",
      "",
      "     ```bash",
      "     SERVICE_DESC=$(aws ecs describe-services --cluster acm-admin-api-prod-20200522 --services acm-admin-api-prod-v2)",
      "     TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')",
      "     TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)",
      "     IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')",
      '     SHA1=$(echo $IMAGE_URL | cut -d ":" -f 2)',
      '     echo "SHA1: $SHA1"',
      "     ```",
    ),
    bodyEn: md(
      "1. **Merge the following PR**",
      "",
      "   - [ ] acm-admin-api: ${pr_url}",
      "",
      "2. **Release to production**",
      "",
      "   - [ ] Run the release command",
      "",
      "     ```bash",
      "     git checkout ${branch}",
      "     git pull origin ${branch}",
      "     yarn build",
      "     cd ecspresso/",
      "     sh migration.sh prod",
      "     sh deploy.sh prod",
      "     ```",
      "",
      "   - [ ] The SHA1 shown by the release command matches the latest master",
      "",
      "3. **Confirm the release**",
      "",
      "   - [ ] Confirm the released SHA1 matches the latest master with the command below",
      "",
      "     ```bash",
      "     SERVICE_DESC=$(aws ecs describe-services --cluster acm-admin-api-prod-20200522 --services acm-admin-api-prod-v2)",
      "     TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')",
      "     TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)",
      "     IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')",
      '     SHA1=$(echo $IMAGE_URL | cut -d ":" -f 2)',
      '     echo "SHA1: $SHA1"',
      "     ```",
    ),
    bodyVi: md(
      "1. **Merge PR sau**",
      "",
      "   - [ ] acm-admin-api: ${pr_url}",
      "",
      "2. **Release lên production**",
      "",
      "   - [ ] Chạy lệnh release",
      "",
      "     ```bash",
      "     git checkout ${branch}",
      "     git pull origin ${branch}",
      "     yarn build",
      "     cd ecspresso/",
      "     sh migration.sh prod",
      "     sh deploy.sh prod",
      "     ```",
      "",
      "   - [ ] SHA1 hiển thị trong lệnh release khớp với master mới nhất",
      "",
      "3. **Xác nhận đã release thành công**",
      "",
      "   - [ ] Dùng lệnh dưới đây để xác nhận SHA1 đã release khớp với master mới nhất",
      "",
      "     ```bash",
      "     SERVICE_DESC=$(aws ecs describe-services --cluster acm-admin-api-prod-20200522 --services acm-admin-api-prod-v2)",
      "     TASK_DEF_ARN=$(echo $SERVICE_DESC | jq -r '.services[0].taskDefinition')",
      "     TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_ARN)",
      "     IMAGE_URL=$(echo $TASK_DEF | jq -r '.taskDefinition.containerDefinitions[0].image')",
      '     SHA1=$(echo $IMAGE_URL | cut -d ":" -f 2)',
      '     echo "SHA1: $SHA1"',
      "     ```",
    ),
  },
  {
    category: "Mall",
    name: "Release acm-api",
    repo: "acm-api",
    bodyJa: md(
      "1. **本番にリリースする**",
      "",
      "   - [ ] PR: ${pr_url}",
      "   - [ ] release コマンドを実行する",
      "",
      "     ```bash",
      "     git checkout ${branch}",
      "     git pull origin ${branch}",
      "     yarn build && cd ecspresso/ && sh deploy.sh prod",
      "     ```",
      "",
      "2. **リリース確認**",
      "",
      "   - [ ] リリースされた SHA1 が最新の master と一致することを確認する",
    ),
    bodyEn: md(
      "1. **Release to production**",
      "",
      "   - [ ] PR: ${pr_url}",
      "   - [ ] Run the release command",
      "",
      "     ```bash",
      "     git checkout ${branch}",
      "     git pull origin ${branch}",
      "     yarn build && cd ecspresso/ && sh deploy.sh prod",
      "     ```",
      "",
      "2. **Confirm release**",
      "",
      "   - [ ] Confirm the released SHA1 matches the latest master",
    ),
    bodyVi: md(
      "1. **Release lên production**",
      "",
      "   - [ ] PR: ${pr_url}",
      "   - [ ] Chạy lệnh release",
      "",
      "     ```bash",
      "     git checkout ${branch}",
      "     git pull origin ${branch}",
      "     yarn build && cd ecspresso/ && sh deploy.sh prod",
      "     ```",
      "",
      "2. **Xác nhận release**",
      "",
      "   - [ ] Xác nhận SHA1 đã release khớp với master mới nhất",
    ),
  },
];

async function seed() {
  // Idempotent: `name` is unique, so re-running skips existing templates.
  const inserted = await db
    .insert(releaseTemplates)
    .values(templates)
    .onConflictDoNothing({ target: releaseTemplates.name })
    .returning({ id: releaseTemplates.id });
  console.log(`Seed complete. Inserted ${inserted.length} template(s).`);
}

seed()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => process.exit());
